'use client'
import { motion, useScroll, useTransform } from "framer-motion"

const ScrollBasedAnimation = () => {
    const { scrollYProgress } = useScroll()
    const background = useTransform(scrollYProgress, [0, 1], ["rgb(86,1,245", "rgb(1,245,13"])


    return (
        <div className='p-5 ' >
            < motion.div style={{
                scaleX: scrollYProgress,
                transformOrigin: "left",
                // background: "blue",
                background,
                position: "sticky",
                top: "0",
                width: "100%",
                height: "20px"
            }} />

            <div>
                <p className='mb-5'>In the fast-paced world of technology, innovation is constantly pushing the boundaries of what is possible. From artificial intelligence to renewable energy, every new development has the potential to reshape industries and change how we live our lives. As we move further into the 21st century, one of the key trends driving technological advancement is the growing integration of data and automation.
                </p>
                <p className='mb-5'>Businesses and organizations are increasingly relying on big data to make more informed decisions. Through data analytics, companies can track consumer behavior, predict market trends, and optimize their operations. Meanwhile, automation is transforming industries such as manufacturing, logistics, and even healthcare. Robots and artificial intelligence are streamlining processes, reducing human error, and increasing efficiency. However, with these advancements come challenges, including concerns about job displacement and the ethical implications of AI decision-making.</p>
                <p className='mb-5'>Another area experiencing rapid growth is renewable energy. With the effects of climate change becoming more apparent, the world is turning to sustainable energy sources such as solar, wind, and hydropower. Innovations in energy storage and distribution are making renewable energy more viable and cost-effective, helping to reduce our reliance on fossil fuels. This shift is crucial not only for environmental sustainability but also for energy security in the future.</p>
                <p className='mb-5'>As exciting as these advancements are, it is important to approach them with a sense of responsibility. Society must consider the ethical, social, and environmental impacts of new technologies. By doing so, we can ensure that innovation leads to a future that benefits everyone, creating a more equitable and sustainable world. In the end, technology should not only serve progress but also the well-being of humanity.</p>
                <p className='mb-5'>In the fast-paced world of technology, innovation is constantly pushing the boundaries of what is possible. From artificial intelligence to renewable energy, every new development has the potential to reshape industries and change how we live our lives. As we move further into the 21st century, one of the key trends driving technological advancement is the growing integration of data and automation.
                </p>
                <p className='mb-5'>Businesses and organizations are increasingly relying on big data to make more informed decisions. Through data analytics, companies can track consumer behavior, predict market trends, and optimize their operations. Meanwhile, automation is transforming industries such as manufacturing, logistics, and even healthcare. Robots and artificial intelligence are streamlining processes, reducing human error, and increasing efficiency. However, with these advancements come challenges, including concerns about job displacement and the ethical implications of AI decision-making.</p>
                <p className='mb-5'>Another area experiencing rapid growth is renewable energy. With the effects of climate change becoming more apparent, the world is turning to sustainable energy sources such as solar, wind, and hydropower. Innovations in energy storage and distribution are making renewable energy more viable and cost-effective, helping to reduce our reliance on fossil fuels. This shift is crucial not only for environmental sustainability but also for energy security in the future.</p>
                <p className='mb-5'>As exciting as these advancements are, it is important to approach them with a sense of responsibility. Society must consider the ethical, social, and environmental impacts of new technologies. By doing so, we can ensure that innovation leads to a future that benefits everyone, creating a more equitable and sustainable world. In the end, technology should not only serve progress but also the well-being of humanity.</p>
                <p className='mb-5'>In the fast-paced world of technology, innovation is constantly pushing the boundaries of what is possible. From artificial intelligence to renewable energy, every new development has the potential to reshape industries and change how we live our lives. As we move further into the 21st century, one of the key trends driving technological advancement is the growing integration of data and automation.
                </p>
                <p className='mb-5'>Businesses and organizations are increasingly relying on big data to make more informed decisions. Through data analytics, companies can track consumer behavior, predict market trends, and optimize their operations. Meanwhile, automation is transforming industries such as manufacturing, logistics, and even healthcare. Robots and artificial intelligence are streamlining processes, reducing human error, and increasing efficiency. However, with these advancements come challenges, including concerns about job displacement and the ethical implications of AI decision-making.</p>
                <p className='mb-5'>Another area experiencing rapid growth is renewable energy. With the effects of climate change becoming more apparent, the world is turning to sustainable energy sources such as solar, wind, and hydropower. Innovations in energy storage and distribution are making renewable energy more viable and cost-effective, helping to reduce our reliance on fossil fuels. This shift is crucial not only for environmental sustainability but also for energy security in the future.</p>
                <p className='mb-5'>As exciting as these advancements are, it is important to approach them with a sense of responsibility. Society must consider the ethical, social, and environmental impacts of new technologies. By doing so, we can ensure that innovation leads to a future that benefits everyone, creating a more equitable and sustainable world. In the end, technology should not only serve progress but also the well-being of humanity.</p>
                <p className='mb-5'>In the fast-paced world of technology, innovation is constantly pushing the boundaries of what is possible. From artificial intelligence to renewable energy, every new development has the potential to reshape industries and change how we live our lives. As we move further into the 21st century, one of the key trends driving technological advancement is the growing integration of data and automation.
                </p>
                <p className='mb-5'>Businesses and organizations are increasingly relying on big data to make more informed decisions. Through data analytics, companies can track consumer behavior, predict market trends, and optimize their operations. Meanwhile, automation is transforming industries such as manufacturing, logistics, and even healthcare. Robots and artificial intelligence are streamlining processes, reducing human error, and increasing efficiency. However, with these advancements come challenges, including concerns about job displacement and the ethical implications of AI decision-making.</p>
                <p className='mb-5'>Another area experiencing rapid growth is renewable energy. With the effects of climate change becoming more apparent, the world is turning to sustainable energy sources such as solar, wind, and hydropower. Innovations in energy storage and distribution are making renewable energy more viable and cost-effective, helping to reduce our reliance on fossil fuels. This shift is crucial not only for environmental sustainability but also for energy security in the future.</p>
                <p className='mb-5'>As exciting as these advancements are, it is important to approach them with a sense of responsibility. Society must consider the ethical, social, and environmental impacts of new technologies. By doing so, we can ensure that innovation leads to a future that benefits everyone, creating a more equitable and sustainable world. In the end, technology should not only serve progress but also the well-being of humanity.</p>
                <p className='mb-5'>In the fast-paced world of technology, innovation is constantly pushing the boundaries of what is possible. From artificial intelligence to renewable energy, every new development has the potential to reshape industries and change how we live our lives. As we move further into the 21st century, one of the key trends driving technological advancement is the growing integration of data and automation.
                </p>
                <p className='mb-5'>Businesses and organizations are increasingly relying on big data to make more informed decisions. Through data analytics, companies can track consumer behavior, predict market trends, and optimize their operations. Meanwhile, automation is transforming industries such as manufacturing, logistics, and even healthcare. Robots and artificial intelligence are streamlining processes, reducing human error, and increasing efficiency. However, with these advancements come challenges, including concerns about job displacement and the ethical implications of AI decision-making.</p>
                <p className='mb-5'>Another area experiencing rapid growth is renewable energy. With the effects of climate change becoming more apparent, the world is turning to sustainable energy sources such as solar, wind, and hydropower. Innovations in energy storage and distribution are making renewable energy more viable and cost-effective, helping to reduce our reliance on fossil fuels. This shift is crucial not only for environmental sustainability but also for energy security in the future.</p>
                <p className='mb-5'>As exciting as these advancements are, it is important to approach them with a sense of responsibility. Society must consider the ethical, social, and environmental impacts of new technologies. By doing so, we can ensure that innovation leads to a future that benefits everyone, creating a more equitable and sustainable world. In the end, technology should not only serve progress but also the well-being of humanity.</p>
                <p className='mb-5'>In the fast-paced world of technology, innovation is constantly pushing the boundaries of what is possible. From artificial intelligence to renewable energy, every new development has the potential to reshape industries and change how we live our lives. As we move further into the 21st century, one of the key trends driving technological advancement is the growing integration of data and automation.
                </p>
                <p className='mb-5'>Businesses and organizations are increasingly relying on big data to make more informed decisions. Through data analytics, companies can track consumer behavior, predict market trends, and optimize their operations. Meanwhile, automation is transforming industries such as manufacturing, logistics, and even healthcare. Robots and artificial intelligence are streamlining processes, reducing human error, and increasing efficiency. However, with these advancements come challenges, including concerns about job displacement and the ethical implications of AI decision-making.</p>
                <p className='mb-5'>Another area experiencing rapid growth is renewable energy. With the effects of climate change becoming more apparent, the world is turning to sustainable energy sources such as solar, wind, and hydropower. Innovations in energy storage and distribution are making renewable energy more viable and cost-effective, helping to reduce our reliance on fossil fuels. This shift is crucial not only for environmental sustainability but also for energy security in the future.</p>
                <p className='mb-5'>As exciting as these advancements are, it is important to approach them with a sense of responsibility. Society must consider the ethical, social, and environmental impacts of new technologies. By doing so, we can ensure that innovation leads to a future that benefits everyone, creating a more equitable and sustainable world. In the end, technology should not only serve progress but also the well-being of humanity.</p>

            </div>

        </div >
    );
};

export default ScrollBasedAnimation;